server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /opt/my-app/html;
    index index.html index.htm;

    # Cấu hình đường dẫn lưu trữ logs cô lập tại /opt/
    access_log /opt/my-app/logs/access.log;
    error_log /opt/my-app/logs/error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
