server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/my-web/html;
    index index.html index.htm;

    # Cấu hình Custom Error Page 404 (từ Bài 2)
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/my-web/html;
        internal;
    }

    # Cấu hình Bảo mật HTTP Basic Authentication cho khu vực quản trị
    location /admin {
        auth_basic "Restricted Admin Area";
        auth_basic_user_file /etc/nginx/.htpasswd;
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
